# -*- coding: utf-8 -*-
"""test_aggregate_g.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XWSJqN7WWWNhgYXX4PA43Vjmqu8216MG
"""

import unittest
import pandas as pd
from aggregate_g import process_merged_G

class TestProcessMergedG(unittest.TestCase):

    def test_process_merged_G(self):
        # Sample test data
        test_data = [
            {'Artifact': 'A', 'Dependencies': 'B', 'Upstream Release Date': '2022-01-01', 'Dependency Release Date': '2022-01-01'},
            {'Artifact': 'C:D', 'Dependencies': 'E:F', 'Upstream Release Date': '2022-01-02', 'Dependency Release Date': '2022-01-02'},
            {'Artifact': 'G:H', 'Dependencies': 'I:J', 'Upstream Release Date': '2022-01-03', 'Dependency Release Date': '2022-01-03'},
        ]

        test_df = pd.DataFrame(test_data)

        result_df = process_merged_G(test_df)

        # Expected output
        expected_columns = ['Source_Group_Id', 'Source Release Date', 'Source Release Year', 'Target_Group_Id', 'Target Release Date', 'Target Release Year', 'Target_First_Release_Date', 'Target_Last_Release_Date', 'Target_Version_Count', 'Source_First_Release_Date', 'Source_Last_Release_Date', 'Source_Version_Count']
        expected_values = [
            ['A', '2022-01-01', '2022', 'B', '2022-01-01', '2022', '2022-01-01', '2022-01-01', 1, '2022-01-01', '2022-01-01', 1],
            ['C', '2022-01-02', '2022', 'E', '2022-01-02', '2022', '2022-01-02', '2022-01-02', 1, '2022-01-02', '2022-01-02', 1],
            ['G', '2022-01-03', '2022', 'I', '2022-01-03', '2022', '2022-01-03', '2022-01-03', 1, '2022-01-03', '2022-01-03', 1],
        ]

        expected_df = pd.DataFrame(expected_values, columns=expected_columns)

        self.assertTrue(result_df.equals(expected_df))

if __name__ == '__main__':
    unittest.main()