# -*- coding: utf-8 -*-
"""test_aggregate_g.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XWSJqN7WWWNhgYXX4PA43Vjmqu8216MG
"""

#!pip install networkx
import unittest
import pandas as pd


from aggregate_g import process_merged_G

class TestProcessMergedG(unittest.TestCase):

    def test_process_merged_G(self):
        # Sample test data
        test_data = [
            {'Artifact': 'net.jini', 'Dependencies': '1', 'Upstream Release Date': '2016-08-10T15:08:35Z[GMT]', 'Dependency Release Date': '2016-08-10T15:08:35Z[GMT]'},
            {'Artifact': 'com.google.javascript:Jar', 'Dependencies': 'com.eriwen:0', 'Upstream Release Date': '0', 'Dependency Release Date': '0'},
            {'Artifact': 'org.slf4j:Jar', 'Dependencies': 'org.terracotta:2', 'Upstream Release Date': '2', 'Dependency Release Date': '2'},

        ]


        test_df = pd.DataFrame(test_data)


        result_df = process_merged_G(test_df)

        # expected output
        expected_columns = ['Source_Group_Id', 'Source Release Date', 'Source Release Year', 'Target_Group_Id', 'Target Release Date', 'Target Release Year', 'Target_First_Release_Date', 'Target_Last_Release_Date', 'Target_Version_Count', 'Source_First_Release_Date', 'Source_Last_Release_Date', 'Source_Version_Count']
        expected_values = [
            ['net.jini', '2016-08-10T15:08:35Z[GMT]', '2016', '1', '2016-08-10T15:08:35Z[GMT]', '2016', '2016-08-10T15:08:35Z[GMT]', '2016-08-10T15:08:35Z[GMT]', 1, '2016-08-10T15:08:35Z[GMT]', '2016-08-10T15:08:35Z[GMT]', 1],

        ]


        expected_df = pd.DataFrame(expected_values, columns=expected_columns)


        self.assertTrue(result_df.equals(expected_df))

if __name__ == '__main__':
    unittest.main()