# -*- coding: utf-8 -*-
"""UnitTest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MIUdEcpESV4-M6um1qXbj0uERD6DueyF
"""

import unittest
import pandas as pd
from io import StringIO

class TestProcessMavenData(unittest.TestCase):

    def setUp(self):
        # Sample CSV data for testing
        self.sample_csv_data = """Artifact,Dependencies,Upstream Release Date,Dependency Release Date
        org.glassfish.distributions:web:3.1.1-b07,org.glassfish.distributions:glassfish:3.1.1-b07,2016-08-10T15:08:35Z[GMT],2016-08-10T15:08:35Z[GMT]
        org.glassfish.connectors:descriptors:3.1-b36,org.glassfish.packager:glassfish-jca:3.1-b36,2016-08-10T15:08:35Z[GMT],2011-08-10T15:08:35Z[GMT]
        """

        self.expected_G_data = {
            'Source_Group_Id': ['org.glassfish.distributions', 'org.glassfish.connectors'],
            'Source_Version': ['3.1.1-b07', '3.1-b36'],
            'Source Release Date': ['2016-08-10T15:08:35Z[GMT]', '2016-08-10T15:08:35Z[GMT]'],
            'Source Release Year': ['2016', '2016'],
            'Target_Group_Id': ['org.glassfish.distributions', 'org.glassfish.packager'],
            'Target_Version': ['3.1.1-b07', '3.1-b36'],
            'Target Release Date': ['2016-08-10T15:08:35Z[GMT]', '2011-08-10T15:08:35Z[GMT]'],
            'Target Release Year': ['2016', '2011'],
            'Target_First_Release_Date': ['2016-08-10T15:08:35Z[GMT]', '2011-08-10T15:08:35Z[GMT]'],
            'Target_Last_Release_Date': ['2016-08-10T15:08:35Z[GMT]', '2011-08-10T15:08:35Z[GMT]'],
            'Version_Count': [1, 1]
        }

        self.expected_GA_data = {
            'Source_Group_Id': ['org.glassfish.distributions', 'org.glassfish.connectors'],
            'Source_Release_Date': ['2016-08-10T15:08:35Z[GMT]', '2016-08-10T15:08:35Z[GMT]'],
            'Source_Release_Year': ['2016', '2016'],
            'Target_Group_Id': ['org.glassfish.distributions', 'org.glassfish.packager'],
            'Target_Artifact_Id': ['glassfish', 'glassfish-jca'],
            'Target_Release_Date': ['2016-08-10T15:08:35Z[GMT]', '2011-08-10T15:08:35Z[GMT]'],
            'Target_Release_Year': ['2016', '2011'],
            'Target_First_Release_Date': ['2016-08-10T15:08:35Z[GMT]', '2011-08-10T15:08:35Z[GMT]'],
            'Target_Last_Release_Date': ['2016-08-10T15:08:35Z[GMT]', '2011-08-10T15:08:35Z[GMT]'],
            'Version_Count': [1, 1]
        }

    def test_process_maven_data(self):
        # Create a sample CSV file from the string data
        csv_file = StringIO(self.sample_csv_data)

        # Call the function with the sample data
        merged_G_df, merged_GA_df = process_maven_data(csv_file)

        # Convert expected data to DataFrames
        expected_G_df = pd.DataFrame(self.expected_G_data)
        expected_GA_df = pd.DataFrame(self.expected_GA_data)

        # Test if the filtered DataFrame G matches the expected DataFrame
        pd.testing.assert_frame_equal(merged_G_df.reset_index(drop=True), expected_G_df.reset_index(drop=True))

        # Test if the filtered DataFrame GA matches the expected DataFrame
        pd.testing.assert_frame_equal(merged_GA_df.reset_index(drop=True), expected_GA_df.reset_index(drop=True))

# Run unit tests
unittest.main(argv=[''], exit=False)