# -*- coding: utf-8 -*-
"""Aggregate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nmZ5WhNTzR-9JFkYU2oINiI1UMKkSNQ4
"""

#FOR GA AND G

def filter_and_calculate(df):
    # Drop unnecessary columns
    # df = df.drop(columns=['Source_Version', 'Target_Version'])
    # df = df.drop(columns=['Source_Artifact_Id', 'Target_Artifact_Id'])

    # Filter groups
    filtered_dfs = []
    for year, group in df.groupby('Target Release Year'):
        # filtered_group = group.drop_duplicates(subset=['Target_Group_Id', 'Target_Artifact_Id'])
        filtered_group = group.drop_duplicates(subset=['Target_Group_Id'])
        filtered_dfs.append(filtered_group)

    # join the filtered DataFrames
    filtered_df = pd.concat(filtered_dfs)

    # first release date
    first_release_dates = df.groupby(['Target_Group_Id'])['Target Release Date'].min().reset_index()
    first_release_dates.columns = ['Target_Group_Id', 'Target_first_release_date']

    # last release date
    last_release_dates = df.groupby(['Target_Group_Id'])['Target Release Date'].max().reset_index()
    last_release_dates.columns = ['Target_Group_Id', 'Target_last_release_date']

    #number of versions for each artifact
    version_counts = df.groupby(['Target_Group_Id']).size().reset_index(name='version_count')

    # Merge
    filtered_df = pd.merge(filtered_df, first_release_dates, on=['Target_Group_Id'])
    filtered_df = pd.merge(filtered_df, last_release_dates, on=['Target_Group_Id'])
    filtered_df = pd.merge(filtered_df, version_counts, on=['Target_Group_Id'])

    return filtered_df